    Задание № 1

In [72]:
import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [73]:
a.shape

(5, 2)

In [74]:
mean_a = [a[:,x].mean() for x in range(a.shape[1])]

In [75]:
mean_a

[2.0, 8.4]

    Задание №2

In [76]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

    Задание №3

In [78]:
a_centered_sp = sum(a_centered[:,0]*a_centered[:,1])
a_centered_sp

8.0

In [82]:
a_centered_sp/(a.shape[0] - 1)

2.0

    Задание №4

In [81]:
a_cov = np.cov(a.T)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])